name: Bicep-StorageAccount-PrivateEndpoint
trigger:
- main
- feature/main

variables:
  resourceGroupName: 'eshopondapr-bicep'
  location: 'westeurope'
  azureSubscription: 'azure-azureDevops'
  resourcePrefix: 'bicep'

pool:
  vmImage: ubuntu-latest

stages:
- stage: Lint
  jobs: 
  - job: LintCode
    displayName: Lint code
    steps:
      - script: |
          az bicep build --file deploy/main.bicep
        name: LintBicepCode
        displayName: Run Bicep linter        
          
        
- stage: Build
  jobs:
  - job: Build
    steps:
    - task: AzureCLI@2  
      displayName: 'build bicep artifact' 
      inputs: 
        azureSubscription: $(azureSubscription) 
        scriptType: 'pscore'  
        scriptLocation: 'inlineScript'  
        inlineScript: 'az bicep build --file main.bicep'  

    - task: PublishBuildArtifacts@1 
      displayName: 'Publish artifact in pipeline' 
      inputs: 
        PathtoPublish: '$(Build.SourcesDirectory)/main.json'  
        ArtifactName: 'finishedTemplate'  
        publishLocation: 'Container' 



- stage: Validate
  jobs: 
  - job: ValidateBicepCode
    displayName: Validate Bicep code
    steps:
      - task: AzureCLI@2
        name: RunPreflightValidation
        displayName: Run preflight validation
        inputs:
          azureSubscription: $(azureSubscription) 
          scriptType: 'pscore'
          scriptLocation: 'inlineScript'
          inlineScript: |
          az deployment group validate  ` 
          az group create --name $(ResourceGroupName) --location $(location) `
              --template-file $(Build.SourcesDirectory)/main.bicep `
              --parameters $(Build.SourcesDirectory)/main.parameters.json `
              --resource-group $(ResourceGroupName) `
              --parameters resourcePrefix=$(resourceprefix)  

- stage: deploy
  jobs:
  - deployment: biceptoAzure
    displayName: 'Deploy bicep to Azure'
    environment: 'AzureDeployment'
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          - task: AzureCLI@2
            displayName: 'deploy bicep template'
            inputs:
              azureSubscription: $(azureSubscription) 
              scriptType: 'pscore'
              scriptLocation: 'inlineScript'
              inlineScript: |
                az group create --name $(ResourceGroupName) --location $(location)
                az deployment group create  `
                --template-file $(Build.SourcesDirectory)/main.bicep `
                --parameters $(Build.SourcesDirectory)/main.parameters.json `
                --resource-group $(ResourceGroupName) `
                --parameters resourcePrefix=$(resourceprefix)