name: Bicep-StorageAccount-PrivateEndpoint
trigger:
- main
- feature/main

variables:
  resourceGroupName: 'eshopondapr-bicep'
  location: 'westeurope'
  azureSubscription: 'azure-azureDevops'
  resourcePrefix: 'bicep'

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - job: Build
    steps:
    - task: AzureCLI@2  
      displayName: 'build bicep artifact' 
      inputs: 
        azureSubscription: $(azureSubscription) 
        scriptType: 'pscore'  
        scriptLocation: 'inlineScript'  
        inlineScript: 'az bicep build --file main.bicep'  

    - task: PublishBuildArtifacts@1 
      displayName: 'Publish artifact in pipeline' 
      inputs: 
        PathtoPublish: '$(Build.SourcesDirectory)/main.json'  
        ArtifactName: 'finishedTemplate'  
        publishLocation: 'Container' 



# - stage: Validate
#   jobs: 
#   - job: ValidateBicepCode
#     displayName: Validate Bicep code
#     steps:
#       - task: AzureCLI@2
#         name: RunPreflightValidation
#         displayName: Run preflight validation
#         inputs:
#           azureSubscription: $(azureSubscription) 
#           scriptType: 'pscore'
#           scriptLocation: 'inlineScript'
#           inlineScript: |
#             az deployment group validate  `
#                             --resource-group $(ResourceGroupName) `
#                             --template-file $(Build.SourcesDirectory)/main.bicep `
#                             --parameters $(Build.SourcesDirectory)/main.parameters.json `
#                             --parameters resourcePrefix=$(resourceprefix)
#                             # az group create --name $(ResourceGroupName) --location $(location) validate  `

- stage: Preview
  jobs: 
  - job: PreviewAzureChanges
    displayName: Preview Azure changes
    steps:
      - task: AzureCLI@2
        name: RunWhatIf
        displayName: Run what-if
        inputs:
              azureSubscription: $(azureSubscription) 
              scriptType: 'pscore'
              scriptLocation: 'inlineScript'
              inlineScript: |
                az group create --name $(ResourceGroupName) --location $(location)            
                az deployment group what-if --name 'what-if' `
                                            --template-file $(Build.SourcesDirectory)/main.bicep `
                                            --parameters $(Build.SourcesDirectory)/main.parameters.json `
                                            --resource-group $(ResourceGroupName) `
                                            --parameters resourcePrefix=$(resourceprefix)
                                                # az group create --name $(ResourceGroupName) --location $(location) what-if   
                                                # az deployment group create 'what-if' `      


- stage: deploy
  jobs:
  - deployment: biceptoAzure
    displayName: 'Deploy bicep to Azure'
    environment: 'AzureDeployment'
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          - task: AzureCLI@2
            displayName: 'deploy bicep template'
            inputs:
              azureSubscription: $(azureSubscription) 
              scriptType: 'pscore'
              scriptLocation: 'inlineScript'
              inlineScript: |
                az group create --name $(ResourceGroupName) --location $(location) 
                az deployment group create `
                        --template-file $(Build.SourcesDirectory)/main.bicep `
                        --parameters $(Build.SourcesDirectory)/main.parameters.json `
                        --resource-group $(ResourceGroupName) `
                        --parameters resourcePrefix=$(resourceprefix)

                #       inlineScript: |
                # az group create --name $(ResourceGroupName) --location $(location)            
                # az deployment group what-if --name 'what-if' `
                #                             --template-file $(Build.SourcesDirectory)/main.bicep `
                #                             --parameters $(Build.SourcesDirectory)/main.parameters.json `
                #                             --resource-group $(ResourceGroupName) `
                #                             --parameters resourcePrefix=$(resourceprefix)
                #                                 # az group create --name $(ResourceGroupName) --location $(location) what-if   
                #                                 # az deployment group create 'what-if' `                
  #               az deployment group create \
  # --name ExampleDeployment \
  # --resource-group ExampleGroup \
  # --template-file <path-to-template> \
  # --parameters storageAccountType=Standard_GRS